// Auto-generated. Do not edit!

// (in-package xnergy_charger_rcu.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ChargerState = require('./ChargerState.js');

//-----------------------------------------------------------

class ChargeFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.status = null;
    }
    else {
      if (initObj.hasOwnProperty('status')) {
        this.status = initObj.status
      }
      else {
        this.status = new ChargerState();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ChargeFeedback
    // Serialize message field [status]
    bufferOffset = ChargerState.serialize(obj.status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ChargeFeedback
    let len;
    let data = new ChargeFeedback(null);
    // Deserialize message field [status]
    data.status = ChargerState.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += ChargerState.getMessageSize(object.status);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'xnergy_charger_rcu/ChargeFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '109992c8e1dfc8ecd7be76c615ba4d7f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    ## Feedback Definition
    ChargerState status
    
    ================================================================================
    MSG: xnergy_charger_rcu/ChargerState
    int16 RCU_NOT_CONNECTED = 250
    
    int16 RCU_IDLE = 0
    
    int16 RCU_RESERVE_0 = 1
    
    int16 RCU_HANDSHAKE_0 = 2
    int16 RCU_HANDSHAKE_1 = 3
    int16 RCU_HANDSHAKE_2 = 4
    
    int16 RCU_CHARGING = 5
    int16 RCU_STOP = 6
    
    int16 RCU_RESERVE_1 = 7
    int16 RCU_RESERVE_2 = 240
    int16 RCU_ERROR = 238
    
    Header header
    int16 state
    string message
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ChargeFeedback(null);
    if (msg.status !== undefined) {
      resolved.status = ChargerState.Resolve(msg.status)
    }
    else {
      resolved.status = new ChargerState()
    }

    return resolved;
    }
};

module.exports = ChargeFeedback;
