// Generated by gencpp from file atc_waypoints/Run_Wp.msg
// DO NOT EDIT!


#ifndef ATC_WAYPOINTS_MESSAGE_RUN_WP_H
#define ATC_WAYPOINTS_MESSAGE_RUN_WP_H

#include <ros/service_traits.h>


#include <atc_waypoints/Run_WpRequest.h>
#include <atc_waypoints/Run_WpResponse.h>


namespace atc_waypoints
{

struct Run_Wp
{

typedef Run_WpRequest Request;
typedef Run_WpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Run_Wp
} // namespace atc_waypoints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atc_waypoints::Run_Wp > {
  static const char* value()
  {
    return "be247a9e980f86ec8f691ab70288ad8a";
  }

  static const char* value(const ::atc_waypoints::Run_Wp&) { return value(); }
};

template<>
struct DataType< ::atc_waypoints::Run_Wp > {
  static const char* value()
  {
    return "atc_waypoints/Run_Wp";
  }

  static const char* value(const ::atc_waypoints::Run_Wp&) { return value(); }
};


// service_traits::MD5Sum< ::atc_waypoints::Run_WpRequest> should match
// service_traits::MD5Sum< ::atc_waypoints::Run_Wp >
template<>
struct MD5Sum< ::atc_waypoints::Run_WpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atc_waypoints::Run_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Run_WpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_waypoints::Run_WpRequest> should match
// service_traits::DataType< ::atc_waypoints::Run_Wp >
template<>
struct DataType< ::atc_waypoints::Run_WpRequest>
{
  static const char* value()
  {
    return DataType< ::atc_waypoints::Run_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Run_WpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atc_waypoints::Run_WpResponse> should match
// service_traits::MD5Sum< ::atc_waypoints::Run_Wp >
template<>
struct MD5Sum< ::atc_waypoints::Run_WpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atc_waypoints::Run_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Run_WpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_waypoints::Run_WpResponse> should match
// service_traits::DataType< ::atc_waypoints::Run_Wp >
template<>
struct DataType< ::atc_waypoints::Run_WpResponse>
{
  static const char* value()
  {
    return DataType< ::atc_waypoints::Run_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Run_WpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATC_WAYPOINTS_MESSAGE_RUN_WP_H
