// Generated by gencpp from file atc_waypoints/Save_Wp.msg
// DO NOT EDIT!


#ifndef ATC_WAYPOINTS_MESSAGE_SAVE_WP_H
#define ATC_WAYPOINTS_MESSAGE_SAVE_WP_H

#include <ros/service_traits.h>


#include <atc_waypoints/Save_WpRequest.h>
#include <atc_waypoints/Save_WpResponse.h>


namespace atc_waypoints
{

struct Save_Wp
{

typedef Save_WpRequest Request;
typedef Save_WpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Save_Wp
} // namespace atc_waypoints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atc_waypoints::Save_Wp > {
  static const char* value()
  {
    return "3ece68834e0f1a84f61883f885f71f9f";
  }

  static const char* value(const ::atc_waypoints::Save_Wp&) { return value(); }
};

template<>
struct DataType< ::atc_waypoints::Save_Wp > {
  static const char* value()
  {
    return "atc_waypoints/Save_Wp";
  }

  static const char* value(const ::atc_waypoints::Save_Wp&) { return value(); }
};


// service_traits::MD5Sum< ::atc_waypoints::Save_WpRequest> should match
// service_traits::MD5Sum< ::atc_waypoints::Save_Wp >
template<>
struct MD5Sum< ::atc_waypoints::Save_WpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atc_waypoints::Save_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Save_WpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_waypoints::Save_WpRequest> should match
// service_traits::DataType< ::atc_waypoints::Save_Wp >
template<>
struct DataType< ::atc_waypoints::Save_WpRequest>
{
  static const char* value()
  {
    return DataType< ::atc_waypoints::Save_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Save_WpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atc_waypoints::Save_WpResponse> should match
// service_traits::MD5Sum< ::atc_waypoints::Save_Wp >
template<>
struct MD5Sum< ::atc_waypoints::Save_WpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atc_waypoints::Save_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Save_WpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_waypoints::Save_WpResponse> should match
// service_traits::DataType< ::atc_waypoints::Save_Wp >
template<>
struct DataType< ::atc_waypoints::Save_WpResponse>
{
  static const char* value()
  {
    return DataType< ::atc_waypoints::Save_Wp >::value();
  }
  static const char* value(const ::atc_waypoints::Save_WpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATC_WAYPOINTS_MESSAGE_SAVE_WP_H
