// Generated by gencpp from file caato2_cmd_mux/change_sub_topicRequest.msg
// DO NOT EDIT!


#ifndef CAATO2_CMD_MUX_MESSAGE_CHANGE_SUB_TOPICREQUEST_H
#define CAATO2_CMD_MUX_MESSAGE_CHANGE_SUB_TOPICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caato2_cmd_mux
{
template <class ContainerAllocator>
struct change_sub_topicRequest_
{
  typedef change_sub_topicRequest_<ContainerAllocator> Type;

  change_sub_topicRequest_()
    : a(0)  {
    }
  change_sub_topicRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct change_sub_topicRequest_

typedef ::caato2_cmd_mux::change_sub_topicRequest_<std::allocator<void> > change_sub_topicRequest;

typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicRequest > change_sub_topicRequestPtr;
typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicRequest const> change_sub_topicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator1> & lhs, const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator1> & lhs, const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace caato2_cmd_mux

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c9fb1a886e81e3162a5c87bf55c072b";
  }

  static const char* value(const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c9fb1a886e81e31ULL;
  static const uint64_t static_value2 = 0x62a5c87bf55c072bULL;
};

template<class ContainerAllocator>
struct DataType< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caato2_cmd_mux/change_sub_topicRequest";
  }

  static const char* value(const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
;
  }

  static const char* value(const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct change_sub_topicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caato2_cmd_mux::change_sub_topicRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAATO2_CMD_MUX_MESSAGE_CHANGE_SUB_TOPICREQUEST_H
