// Generated by gencpp from file caato2_cmd_mux/change_sub_topicResponse.msg
// DO NOT EDIT!


#ifndef CAATO2_CMD_MUX_MESSAGE_CHANGE_SUB_TOPICRESPONSE_H
#define CAATO2_CMD_MUX_MESSAGE_CHANGE_SUB_TOPICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caato2_cmd_mux
{
template <class ContainerAllocator>
struct change_sub_topicResponse_
{
  typedef change_sub_topicResponse_<ContainerAllocator> Type;

  change_sub_topicResponse_()
    : result(false)  {
    }
  change_sub_topicResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct change_sub_topicResponse_

typedef ::caato2_cmd_mux::change_sub_topicResponse_<std::allocator<void> > change_sub_topicResponse;

typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicResponse > change_sub_topicResponsePtr;
typedef boost::shared_ptr< ::caato2_cmd_mux::change_sub_topicResponse const> change_sub_topicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator1> & lhs, const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator1> & lhs, const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace caato2_cmd_mux

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caato2_cmd_mux/change_sub_topicResponse";
  }

  static const char* value(const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct change_sub_topicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caato2_cmd_mux::change_sub_topicResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAATO2_CMD_MUX_MESSAGE_CHANGE_SUB_TOPICRESPONSE_H
