(cl:defpackage xnergy_charger_rcu-msg
  (:use )
  (:export
   "<CHARGEACTION>"
   "CHARGEACTION"
   "<CHARGEACTIONFEEDBACK>"
   "CHARGEACTIONFEEDBACK"
   "<CHARGEACTIONGOAL>"
   "CHARGEACTIONGOAL"
   "<CHARGEACTIONRESULT>"
   "CHARGEACTIONRESULT"
   "<CHARGEFEEDBACK>"
   "CHARGEFEEDBACK"
   "<CHARGEGOAL>"
   "CHARGEGOAL"
   "<CHARGERESULT>"
   "CHARGERESULT"
   "<CHARGERSTATE>"
   "CHARGERSTATE"
  ))

