; Auto-generated. Do not edit!


(cl:in-package xnergy_charger_rcu-msg)


;//! \htmlinclude ChargeGoal.msg.html

(cl:defclass <ChargeGoal> (roslisp-msg-protocol:ros-message)
  ((enable_charge
    :reader enable_charge
    :initarg :enable_charge
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ChargeGoal (<ChargeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name xnergy_charger_rcu-msg:<ChargeGoal> is deprecated: use xnergy_charger_rcu-msg:ChargeGoal instead.")))

(cl:ensure-generic-function 'enable_charge-val :lambda-list '(m))
(cl:defmethod enable_charge-val ((m <ChargeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader xnergy_charger_rcu-msg:enable_charge-val is deprecated.  Use xnergy_charger_rcu-msg:enable_charge instead.")
  (enable_charge m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargeGoal>) ostream)
  "Serializes a message object of type '<ChargeGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'enable_charge) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargeGoal>) istream)
  "Deserializes a message object of type '<ChargeGoal>"
    (cl:setf (cl:slot-value msg 'enable_charge) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargeGoal>)))
  "Returns string type for a message object of type '<ChargeGoal>"
  "xnergy_charger_rcu/ChargeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargeGoal)))
  "Returns string type for a message object of type 'ChargeGoal"
  "xnergy_charger_rcu/ChargeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargeGoal>)))
  "Returns md5sum for a message object of type '<ChargeGoal>"
  "f613c78a671dd6ea2f038c0a4c2f0c24")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargeGoal)))
  "Returns md5sum for a message object of type 'ChargeGoal"
  "f613c78a671dd6ea2f038c0a4c2f0c24")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargeGoal>)))
  "Returns full string definition for message of type '<ChargeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%## Goal Definition~%bool enable_charge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargeGoal)))
  "Returns full string definition for message of type 'ChargeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%## Goal Definition~%bool enable_charge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargeGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargeGoal
    (cl:cons ':enable_charge (enable_charge msg))
))
