// Generated by gencpp from file atc_msgs/AGVStatus.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_AGVSTATUS_H
#define ATC_MSGS_MESSAGE_AGVSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atc_msgs
{
template <class ContainerAllocator>
struct AGVStatus_
{
  typedef AGVStatus_<ContainerAllocator> Type;

  AGVStatus_()
    : movement_mode(0)
    , agv_state(0)
    , status_message()  {
    }
  AGVStatus_(const ContainerAllocator& _alloc)
    : movement_mode(0)
    , agv_state(0)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _movement_mode_type;
  _movement_mode_type movement_mode;

   typedef int8_t _agv_state_type;
  _agv_state_type agv_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::atc_msgs::AGVStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atc_msgs::AGVStatus_<ContainerAllocator> const> ConstPtr;

}; // struct AGVStatus_

typedef ::atc_msgs::AGVStatus_<std::allocator<void> > AGVStatus;

typedef boost::shared_ptr< ::atc_msgs::AGVStatus > AGVStatusPtr;
typedef boost::shared_ptr< ::atc_msgs::AGVStatus const> AGVStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atc_msgs::AGVStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atc_msgs::AGVStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atc_msgs::AGVStatus_<ContainerAllocator1> & lhs, const ::atc_msgs::AGVStatus_<ContainerAllocator2> & rhs)
{
  return lhs.movement_mode == rhs.movement_mode &&
    lhs.agv_state == rhs.agv_state &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atc_msgs::AGVStatus_<ContainerAllocator1> & lhs, const ::atc_msgs::AGVStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::AGVStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::AGVStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::AGVStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::AGVStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::AGVStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::AGVStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atc_msgs::AGVStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "010f36062e337e714a6af437b8b2868d";
  }

  static const char* value(const ::atc_msgs::AGVStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x010f36062e337e71ULL;
  static const uint64_t static_value2 = 0x4a6af437b8b2868dULL;
};

template<class ContainerAllocator>
struct DataType< ::atc_msgs::AGVStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atc_msgs/AGVStatus";
  }

  static const char* value(const ::atc_msgs::AGVStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atc_msgs::AGVStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response fields\n"
"int8 movement_mode\n"
"int8 agv_state\n"
"string status_message\n"
;
  }

  static const char* value(const ::atc_msgs::AGVStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atc_msgs::AGVStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movement_mode);
      stream.next(m.agv_state);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AGVStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atc_msgs::AGVStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atc_msgs::AGVStatus_<ContainerAllocator>& v)
  {
    s << indent << "movement_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.movement_mode);
    s << indent << "agv_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.agv_state);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATC_MSGS_MESSAGE_AGVSTATUS_H
