// Generated by gencpp from file atc_msgs/Click_To_TurnRequest.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_CLICK_TO_TURNREQUEST_H
#define ATC_MSGS_MESSAGE_CLICK_TO_TURNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atc_msgs
{
template <class ContainerAllocator>
struct Click_To_TurnRequest_
{
  typedef Click_To_TurnRequest_<ContainerAllocator> Type;

  Click_To_TurnRequest_()
    : cmd_heading_deg(0.0)  {
    }
  Click_To_TurnRequest_(const ContainerAllocator& _alloc)
    : cmd_heading_deg(0.0)  {
  (void)_alloc;
    }



   typedef double _cmd_heading_deg_type;
  _cmd_heading_deg_type cmd_heading_deg;





  typedef boost::shared_ptr< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Click_To_TurnRequest_

typedef ::atc_msgs::Click_To_TurnRequest_<std::allocator<void> > Click_To_TurnRequest;

typedef boost::shared_ptr< ::atc_msgs::Click_To_TurnRequest > Click_To_TurnRequestPtr;
typedef boost::shared_ptr< ::atc_msgs::Click_To_TurnRequest const> Click_To_TurnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator1> & lhs, const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_heading_deg == rhs.cmd_heading_deg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator1> & lhs, const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e36fc7f505f9217e00e5d29fa5366eeb";
  }

  static const char* value(const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe36fc7f505f9217eULL;
  static const uint64_t static_value2 = 0x00e5d29fa5366eebULL;
};

template<class ContainerAllocator>
struct DataType< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atc_msgs/Click_To_TurnRequest";
  }

  static const char* value(const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Incoming parameter of the service.\n"
"float64 cmd_heading_deg\n"
;
  }

  static const char* value(const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_heading_deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Click_To_TurnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atc_msgs::Click_To_TurnRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd_heading_deg: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_heading_deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATC_MSGS_MESSAGE_CLICK_TO_TURNREQUEST_H
