// Generated by gencpp from file atc_msgs/Dock_To_Tag.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_DOCK_TO_TAG_H
#define ATC_MSGS_MESSAGE_DOCK_TO_TAG_H

#include <ros/service_traits.h>


#include <atc_msgs/Dock_To_TagRequest.h>
#include <atc_msgs/Dock_To_TagResponse.h>


namespace atc_msgs
{

struct Dock_To_Tag
{

typedef Dock_To_TagRequest Request;
typedef Dock_To_TagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dock_To_Tag
} // namespace atc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atc_msgs::Dock_To_Tag > {
  static const char* value()
  {
    return "67c5dc84dc7bf2515da8be60c1d622ff";
  }

  static const char* value(const ::atc_msgs::Dock_To_Tag&) { return value(); }
};

template<>
struct DataType< ::atc_msgs::Dock_To_Tag > {
  static const char* value()
  {
    return "atc_msgs/Dock_To_Tag";
  }

  static const char* value(const ::atc_msgs::Dock_To_Tag&) { return value(); }
};


// service_traits::MD5Sum< ::atc_msgs::Dock_To_TagRequest> should match
// service_traits::MD5Sum< ::atc_msgs::Dock_To_Tag >
template<>
struct MD5Sum< ::atc_msgs::Dock_To_TagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Dock_To_Tag >::value();
  }
  static const char* value(const ::atc_msgs::Dock_To_TagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Dock_To_TagRequest> should match
// service_traits::DataType< ::atc_msgs::Dock_To_Tag >
template<>
struct DataType< ::atc_msgs::Dock_To_TagRequest>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Dock_To_Tag >::value();
  }
  static const char* value(const ::atc_msgs::Dock_To_TagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atc_msgs::Dock_To_TagResponse> should match
// service_traits::MD5Sum< ::atc_msgs::Dock_To_Tag >
template<>
struct MD5Sum< ::atc_msgs::Dock_To_TagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Dock_To_Tag >::value();
  }
  static const char* value(const ::atc_msgs::Dock_To_TagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Dock_To_TagResponse> should match
// service_traits::DataType< ::atc_msgs::Dock_To_Tag >
template<>
struct DataType< ::atc_msgs::Dock_To_TagResponse>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Dock_To_Tag >::value();
  }
  static const char* value(const ::atc_msgs::Dock_To_TagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATC_MSGS_MESSAGE_DOCK_TO_TAG_H
