// Generated by gencpp from file atc_msgs/Dock_To_TagResponse.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_DOCK_TO_TAGRESPONSE_H
#define ATC_MSGS_MESSAGE_DOCK_TO_TAGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atc_msgs
{
template <class ContainerAllocator>
struct Dock_To_TagResponse_
{
  typedef Dock_To_TagResponse_<ContainerAllocator> Type;

  Dock_To_TagResponse_()
    : movement_mode(0)
    , agv_state(0)
    , status_message()
    , dock_message()  {
    }
  Dock_To_TagResponse_(const ContainerAllocator& _alloc)
    : movement_mode(0)
    , agv_state(0)
    , status_message(_alloc)
    , dock_message(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _movement_mode_type;
  _movement_mode_type movement_mode;

   typedef int8_t _agv_state_type;
  _agv_state_type agv_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dock_message_type;
  _dock_message_type dock_message;





  typedef boost::shared_ptr< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Dock_To_TagResponse_

typedef ::atc_msgs::Dock_To_TagResponse_<std::allocator<void> > Dock_To_TagResponse;

typedef boost::shared_ptr< ::atc_msgs::Dock_To_TagResponse > Dock_To_TagResponsePtr;
typedef boost::shared_ptr< ::atc_msgs::Dock_To_TagResponse const> Dock_To_TagResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator1> & lhs, const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator2> & rhs)
{
  return lhs.movement_mode == rhs.movement_mode &&
    lhs.agv_state == rhs.agv_state &&
    lhs.status_message == rhs.status_message &&
    lhs.dock_message == rhs.dock_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator1> & lhs, const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cda3a5eb259c84cd32dd99e481df4892";
  }

  static const char* value(const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcda3a5eb259c84cdULL;
  static const uint64_t static_value2 = 0x32dd99e481df4892ULL;
};

template<class ContainerAllocator>
struct DataType< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atc_msgs/Dock_To_TagResponse";
  }

  static const char* value(const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response fields\n"
"int8 movement_mode\n"
"int8 agv_state\n"
"string status_message\n"
"string dock_message\n"
"\n"
"\n"
;
  }

  static const char* value(const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movement_mode);
      stream.next(m.agv_state);
      stream.next(m.status_message);
      stream.next(m.dock_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dock_To_TagResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atc_msgs::Dock_To_TagResponse_<ContainerAllocator>& v)
  {
    s << indent << "movement_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.movement_mode);
    s << indent << "agv_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.agv_state);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
    s << indent << "dock_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dock_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATC_MSGS_MESSAGE_DOCK_TO_TAGRESPONSE_H
