// Generated by gencpp from file atc_msgs/Navigate_To_Trolley.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_NAVIGATE_TO_TROLLEY_H
#define ATC_MSGS_MESSAGE_NAVIGATE_TO_TROLLEY_H

#include <ros/service_traits.h>


#include <atc_msgs/Navigate_To_TrolleyRequest.h>
#include <atc_msgs/Navigate_To_TrolleyResponse.h>


namespace atc_msgs
{

struct Navigate_To_Trolley
{

typedef Navigate_To_TrolleyRequest Request;
typedef Navigate_To_TrolleyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Navigate_To_Trolley
} // namespace atc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atc_msgs::Navigate_To_Trolley > {
  static const char* value()
  {
    return "9b673f27308e92379ce696241f36bf24";
  }

  static const char* value(const ::atc_msgs::Navigate_To_Trolley&) { return value(); }
};

template<>
struct DataType< ::atc_msgs::Navigate_To_Trolley > {
  static const char* value()
  {
    return "atc_msgs/Navigate_To_Trolley";
  }

  static const char* value(const ::atc_msgs::Navigate_To_Trolley&) { return value(); }
};


// service_traits::MD5Sum< ::atc_msgs::Navigate_To_TrolleyRequest> should match
// service_traits::MD5Sum< ::atc_msgs::Navigate_To_Trolley >
template<>
struct MD5Sum< ::atc_msgs::Navigate_To_TrolleyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Navigate_To_Trolley >::value();
  }
  static const char* value(const ::atc_msgs::Navigate_To_TrolleyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Navigate_To_TrolleyRequest> should match
// service_traits::DataType< ::atc_msgs::Navigate_To_Trolley >
template<>
struct DataType< ::atc_msgs::Navigate_To_TrolleyRequest>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Navigate_To_Trolley >::value();
  }
  static const char* value(const ::atc_msgs::Navigate_To_TrolleyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atc_msgs::Navigate_To_TrolleyResponse> should match
// service_traits::MD5Sum< ::atc_msgs::Navigate_To_Trolley >
template<>
struct MD5Sum< ::atc_msgs::Navigate_To_TrolleyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Navigate_To_Trolley >::value();
  }
  static const char* value(const ::atc_msgs::Navigate_To_TrolleyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Navigate_To_TrolleyResponse> should match
// service_traits::DataType< ::atc_msgs::Navigate_To_Trolley >
template<>
struct DataType< ::atc_msgs::Navigate_To_TrolleyResponse>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Navigate_To_Trolley >::value();
  }
  static const char* value(const ::atc_msgs::Navigate_To_TrolleyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATC_MSGS_MESSAGE_NAVIGATE_TO_TROLLEY_H
