// Generated by gencpp from file atc_msgs/Navigate_To_TrolleyRequest.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_NAVIGATE_TO_TROLLEYREQUEST_H
#define ATC_MSGS_MESSAGE_NAVIGATE_TO_TROLLEYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atc_msgs
{
template <class ContainerAllocator>
struct Navigate_To_TrolleyRequest_
{
  typedef Navigate_To_TrolleyRequest_<ContainerAllocator> Type;

  Navigate_To_TrolleyRequest_()
    : navigateToTrolley(false)  {
    }
  Navigate_To_TrolleyRequest_(const ContainerAllocator& _alloc)
    : navigateToTrolley(false)  {
  (void)_alloc;
    }



   typedef uint8_t _navigateToTrolley_type;
  _navigateToTrolley_type navigateToTrolley;





  typedef boost::shared_ptr< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Navigate_To_TrolleyRequest_

typedef ::atc_msgs::Navigate_To_TrolleyRequest_<std::allocator<void> > Navigate_To_TrolleyRequest;

typedef boost::shared_ptr< ::atc_msgs::Navigate_To_TrolleyRequest > Navigate_To_TrolleyRequestPtr;
typedef boost::shared_ptr< ::atc_msgs::Navigate_To_TrolleyRequest const> Navigate_To_TrolleyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator1> & lhs, const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.navigateToTrolley == rhs.navigateToTrolley;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator1> & lhs, const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48d6c5ca39fd5fc091d5ffcc65cdf7e7";
  }

  static const char* value(const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48d6c5ca39fd5fc0ULL;
  static const uint64_t static_value2 = 0x91d5ffcc65cdf7e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atc_msgs/Navigate_To_TrolleyRequest";
  }

  static const char* value(const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Incoming parameter of the service. For Navigation to Trolley\n"
"bool navigateToTrolley\n"
;
  }

  static const char* value(const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.navigateToTrolley);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Navigate_To_TrolleyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atc_msgs::Navigate_To_TrolleyRequest_<ContainerAllocator>& v)
  {
    s << indent << "navigateToTrolley: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.navigateToTrolley);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATC_MSGS_MESSAGE_NAVIGATE_TO_TROLLEYREQUEST_H
