// Generated by gencpp from file atc_msgs/Reset_ClearCostMap.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_RESET_CLEARCOSTMAP_H
#define ATC_MSGS_MESSAGE_RESET_CLEARCOSTMAP_H

#include <ros/service_traits.h>


#include <atc_msgs/Reset_ClearCostMapRequest.h>
#include <atc_msgs/Reset_ClearCostMapResponse.h>


namespace atc_msgs
{

struct Reset_ClearCostMap
{

typedef Reset_ClearCostMapRequest Request;
typedef Reset_ClearCostMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset_ClearCostMap
} // namespace atc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atc_msgs::Reset_ClearCostMap > {
  static const char* value()
  {
    return "4e81401608ff091117805de30b410139";
  }

  static const char* value(const ::atc_msgs::Reset_ClearCostMap&) { return value(); }
};

template<>
struct DataType< ::atc_msgs::Reset_ClearCostMap > {
  static const char* value()
  {
    return "atc_msgs/Reset_ClearCostMap";
  }

  static const char* value(const ::atc_msgs::Reset_ClearCostMap&) { return value(); }
};


// service_traits::MD5Sum< ::atc_msgs::Reset_ClearCostMapRequest> should match
// service_traits::MD5Sum< ::atc_msgs::Reset_ClearCostMap >
template<>
struct MD5Sum< ::atc_msgs::Reset_ClearCostMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Reset_ClearCostMap >::value();
  }
  static const char* value(const ::atc_msgs::Reset_ClearCostMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Reset_ClearCostMapRequest> should match
// service_traits::DataType< ::atc_msgs::Reset_ClearCostMap >
template<>
struct DataType< ::atc_msgs::Reset_ClearCostMapRequest>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Reset_ClearCostMap >::value();
  }
  static const char* value(const ::atc_msgs::Reset_ClearCostMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atc_msgs::Reset_ClearCostMapResponse> should match
// service_traits::MD5Sum< ::atc_msgs::Reset_ClearCostMap >
template<>
struct MD5Sum< ::atc_msgs::Reset_ClearCostMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Reset_ClearCostMap >::value();
  }
  static const char* value(const ::atc_msgs::Reset_ClearCostMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Reset_ClearCostMapResponse> should match
// service_traits::DataType< ::atc_msgs::Reset_ClearCostMap >
template<>
struct DataType< ::atc_msgs::Reset_ClearCostMapResponse>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Reset_ClearCostMap >::value();
  }
  static const char* value(const ::atc_msgs::Reset_ClearCostMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATC_MSGS_MESSAGE_RESET_CLEARCOSTMAP_H
