// Generated by gencpp from file atc_msgs/Run_Specific_Wp.msg
// DO NOT EDIT!


#ifndef ATC_MSGS_MESSAGE_RUN_SPECIFIC_WP_H
#define ATC_MSGS_MESSAGE_RUN_SPECIFIC_WP_H

#include <ros/service_traits.h>


#include <atc_msgs/Run_Specific_WpRequest.h>
#include <atc_msgs/Run_Specific_WpResponse.h>


namespace atc_msgs
{

struct Run_Specific_Wp
{

typedef Run_Specific_WpRequest Request;
typedef Run_Specific_WpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Run_Specific_Wp
} // namespace atc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atc_msgs::Run_Specific_Wp > {
  static const char* value()
  {
    return "23ec7c550dce6f4814e4ea3d6baccb5b";
  }

  static const char* value(const ::atc_msgs::Run_Specific_Wp&) { return value(); }
};

template<>
struct DataType< ::atc_msgs::Run_Specific_Wp > {
  static const char* value()
  {
    return "atc_msgs/Run_Specific_Wp";
  }

  static const char* value(const ::atc_msgs::Run_Specific_Wp&) { return value(); }
};


// service_traits::MD5Sum< ::atc_msgs::Run_Specific_WpRequest> should match
// service_traits::MD5Sum< ::atc_msgs::Run_Specific_Wp >
template<>
struct MD5Sum< ::atc_msgs::Run_Specific_WpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Run_Specific_Wp >::value();
  }
  static const char* value(const ::atc_msgs::Run_Specific_WpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Run_Specific_WpRequest> should match
// service_traits::DataType< ::atc_msgs::Run_Specific_Wp >
template<>
struct DataType< ::atc_msgs::Run_Specific_WpRequest>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Run_Specific_Wp >::value();
  }
  static const char* value(const ::atc_msgs::Run_Specific_WpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atc_msgs::Run_Specific_WpResponse> should match
// service_traits::MD5Sum< ::atc_msgs::Run_Specific_Wp >
template<>
struct MD5Sum< ::atc_msgs::Run_Specific_WpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atc_msgs::Run_Specific_Wp >::value();
  }
  static const char* value(const ::atc_msgs::Run_Specific_WpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atc_msgs::Run_Specific_WpResponse> should match
// service_traits::DataType< ::atc_msgs::Run_Specific_Wp >
template<>
struct DataType< ::atc_msgs::Run_Specific_WpResponse>
{
  static const char* value()
  {
    return DataType< ::atc_msgs::Run_Specific_Wp >::value();
  }
  static const char* value(const ::atc_msgs::Run_Specific_WpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATC_MSGS_MESSAGE_RUN_SPECIFIC_WP_H
