(cl:defpackage plc_modbus_node-msg
  (:use )
  (:export
   "<BYTEARRAY>"
   "BYTEARRAY"
   "<MULTIBYTEARRAY>"
   "MULTIBYTEARRAY"
   "<MULTIUINT16ARRAY>"
   "MULTIUINT16ARRAY"
   "<UINT16ARRAY>"
   "UINT16ARRAY"
   "<FORKLIFT_SENSORS>"
   "FORKLIFT_SENSORS"
   "<MAIN_CONTROLLER>"
   "MAIN_CONTROLLER"
   "<REGISTER_MSG>"
   "REGISTER_MSG"
   "<ROBOTEQ_SENSORS>"
   "ROBOTEQ_SENSORS"
   "<XNERGY_SENSORS>"
   "XNERGY_SENSORS"
  ))

