; Auto-generated. Do not edit!


(cl:in-package atc_msgs-srv)


;//! \htmlinclude Run_Specific_Wp-request.msg.html

(cl:defclass <Run_Specific_Wp-request> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type move_base_msgs-msg:MoveBaseGoal
    :initform (cl:make-instance 'move_base_msgs-msg:MoveBaseGoal)))
)

(cl:defclass Run_Specific_Wp-request (<Run_Specific_Wp-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Run_Specific_Wp-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Run_Specific_Wp-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name atc_msgs-srv:<Run_Specific_Wp-request> is deprecated: use atc_msgs-srv:Run_Specific_Wp-request instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <Run_Specific_Wp-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader atc_msgs-srv:goal-val is deprecated.  Use atc_msgs-srv:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Run_Specific_Wp-request>) ostream)
  "Serializes a message object of type '<Run_Specific_Wp-request>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Run_Specific_Wp-request>) istream)
  "Deserializes a message object of type '<Run_Specific_Wp-request>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Run_Specific_Wp-request>)))
  "Returns string type for a service object of type '<Run_Specific_Wp-request>"
  "atc_msgs/Run_Specific_WpRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Run_Specific_Wp-request)))
  "Returns string type for a service object of type 'Run_Specific_Wp-request"
  "atc_msgs/Run_Specific_WpRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Run_Specific_Wp-request>)))
  "Returns md5sum for a message object of type '<Run_Specific_Wp-request>"
  "23ec7c550dce6f4814e4ea3d6baccb5b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Run_Specific_Wp-request)))
  "Returns md5sum for a message object of type 'Run_Specific_Wp-request"
  "23ec7c550dce6f4814e4ea3d6baccb5b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Run_Specific_Wp-request>)))
  "Returns full string definition for message of type '<Run_Specific_Wp-request>"
  (cl:format cl:nil "move_base_msgs/MoveBaseGoal goal       ~%~%================================================================================~%MSG: move_base_msgs/MoveBaseGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Run_Specific_Wp-request)))
  "Returns full string definition for message of type 'Run_Specific_Wp-request"
  (cl:format cl:nil "move_base_msgs/MoveBaseGoal goal       ~%~%================================================================================~%MSG: move_base_msgs/MoveBaseGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Run_Specific_Wp-request>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Run_Specific_Wp-request>))
  "Converts a ROS message object to a list"
  (cl:list 'Run_Specific_Wp-request
    (cl:cons ':goal (goal msg))
))
;//! \htmlinclude Run_Specific_Wp-response.msg.html

(cl:defclass <Run_Specific_Wp-response> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass Run_Specific_Wp-response (<Run_Specific_Wp-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Run_Specific_Wp-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Run_Specific_Wp-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name atc_msgs-srv:<Run_Specific_Wp-response> is deprecated: use atc_msgs-srv:Run_Specific_Wp-response instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <Run_Specific_Wp-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader atc_msgs-srv:success-val is deprecated.  Use atc_msgs-srv:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Run_Specific_Wp-response>) ostream)
  "Serializes a message object of type '<Run_Specific_Wp-response>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Run_Specific_Wp-response>) istream)
  "Deserializes a message object of type '<Run_Specific_Wp-response>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Run_Specific_Wp-response>)))
  "Returns string type for a service object of type '<Run_Specific_Wp-response>"
  "atc_msgs/Run_Specific_WpResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Run_Specific_Wp-response)))
  "Returns string type for a service object of type 'Run_Specific_Wp-response"
  "atc_msgs/Run_Specific_WpResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Run_Specific_Wp-response>)))
  "Returns md5sum for a message object of type '<Run_Specific_Wp-response>"
  "23ec7c550dce6f4814e4ea3d6baccb5b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Run_Specific_Wp-response)))
  "Returns md5sum for a message object of type 'Run_Specific_Wp-response"
  "23ec7c550dce6f4814e4ea3d6baccb5b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Run_Specific_Wp-response>)))
  "Returns full string definition for message of type '<Run_Specific_Wp-response>"
  (cl:format cl:nil "bool success     ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Run_Specific_Wp-response)))
  "Returns full string definition for message of type 'Run_Specific_Wp-response"
  (cl:format cl:nil "bool success     ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Run_Specific_Wp-response>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Run_Specific_Wp-response>))
  "Converts a ROS message object to a list"
  (cl:list 'Run_Specific_Wp-response
    (cl:cons ':success (success msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'Run_Specific_Wp)))
  'Run_Specific_Wp-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'Run_Specific_Wp)))
  'Run_Specific_Wp-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Run_Specific_Wp)))
  "Returns string type for a service object of type '<Run_Specific_Wp>"
  "atc_msgs/Run_Specific_Wp")